import "./globals.css";
import { Inter } from "next/font/google";

import { NavBar, ScrollToTop, Footer } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Muhamed Safwat || Web dev",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico"],
    apple: ["apple-touch-icon.png"],
    shortcut: ["apple-touch-icon.png"],
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={inter.className + "relative"}>
        <NavBar />
        <main className="text-gray-800 relative">
          {children}
          <ScrollToTop />
        </main>
      </body>
    </html>
  );
}
