import "./globals.css";
import { Inter } from "next/font/google";

import { NavBar, ScrollToTop, Footer } from "@/components";
import AuthContext from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Muhamed Safwat || Web dev",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico"],
    apple: ["apple-touch-icon.png"],
    shortcut: ["apple-touch-icon.png"],
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <AuthContext>
      <html className="scroll-smooth" lang="en">
        <body
          className={inter.className + "relative w-screen overflow-x-hidden"}
        >
          <NavBar />
          <main className="text-gray-800 relative">
            {children}
            <ScrollToTop />
          </main>
        </body>
      </html>
    </AuthContext>
  );
}
